### ISSUE TITLE
Unknown "array" helper

### ISSUE THREAD

**Issue by bummzack** [gmurphey/ember-searchable-collection#1]
The examples in the documentation use an array helper, which isn't installed with the addon. After installing https://github.com/kellyselden/ember-array-helper, it works.

Maybe add the helper to your dependencies, or mention it in the installation instructions?
Other than that, great addon. Just what I needed.

**Comment by gmurphey** [comment]
Ah, yes. This is due to laziness on my part. I'll find some time today to update the documentation. Thanks for pointing this out!
